### PR TITLE
Batch fix

### PR DESCRIPTION
**Pull request by solareon**
Rewrite of batch processing. Loads images into a list and then posts them all together. This limits batch count/size to 10 due to the discord attachment limit but most bots usually use batch count/size of 4.

### CODE REVIEW

**Comment by Kilvoctu** [comment]
Heya, thanks for your work. 👍 I checked out the changes and well, this essentially only reverts my previous PR #134 without addressing the points I made in discussion #153. I need those points done.  
I would have done the simple reverting myself (the branch mentioned in #153 actually does so) if not for the two points of contention, as people have talked about how annoying the new behavior is, and how it's a "huge waste of mental resources", to the point where I had zero fun to work on this project and had to take a break, despite having a detailed outline in mind on how to execute my ideas.

If you can, please look into applying these changes. I'll tell you precisely what I had planned.  

- Do not send multiple images. Send only one image in a grid. The Web UI api doesn't support this, so AIYA has to manually create the grid from the images generated. This was the [stackoverflow post](https://stackoverflow.com/questions/37921295/python-pil-image-make-3x3-grid-from-sequence-images) I was looking into to do so. I've prototyped it and it does work.  
It will remove the 10 attachment limit, which I was aware of, and AIYA can instead impose any arbitrary limit. I was aiming for 25 limit, and the grid for each 2 to 25 needs to look sensible; e.g., 2x1, 2x2, 3x2, 3x3, etc (no really long or tall grids)

- The buttons need to be able to interact with every image. Currently they only work for one of them. This restriction was the main catalyst for creating the mentioned PR. This one is a bit more tricky, because the infrastructure for creating Discord buttons is quite poor, but I had a solution that should work conceptually. 🤔  
A new view (this is the container for the buttons) needs to be created that handles the batches; name it BatchView. If batch entered is more than 1, BatchView is attached to initial message instead of the current DrawView. It has to go on the initial message, not output message; it's the only place where it can find the running event loop.  
BatchView should know exactly how many images are requested and create the respective number of buttons (2 to 25). Discord supports up to 5 rows of 5 buttons per row, so that's why 25 is selected. When clicking on any button in this view, it should update the view from BatchView to DrawView, and finally DrawView's buttons should have the information pertaining to the corresponding image in the grid.

If you can do it, really awesome. If not, that's all right too; I do plan on doing this eventually. Even just the first point would be an improvement in the interim, now that I think about it, and the second point can be split into a future PR/update.  
Thanks again for the PR. I really do appreciate the gesture 👍👍 I can answer any questions you have.

**Comment by solareon** [comment]
No worries. I didn't see the previous PR. I'll keep tinkering with it and update it when I get it figured out.

**Comment by Kilvoctu** [comment]
It's all right, I don't expect anyone to check PR history. I was just giving context on why this PR isn't merge-able as is.  

I'm super appreciative about the willingness to contribute already, and magnitudes moreso if you can tackle those points. This repo's projects list is fairly large, and that right now is high up there on my priorities.

**Comment by solareon** [comment]
Well small update I think I have all the logic sorted out to get the images chunked up into a max of 25 grids. If my brain isn't smooth it should in theory work out to whatever the max batch count/size that A1111 supports. I'm reworking the stealthpng stuff out into a function now and should be testing it shortly. 

My plan is to add a drop down to pick the correct picture for the button interactions that will be under each grid. This method will require locally saving the images since there isn't a clean method to get the attachment URLs at least with how we structure the interactions currently.

**Comment by solareon** [comment]
The last commit generates the batches correctly. I tested up to like 60 and it properly batched them in chunks of 25. I'll be working on the dropdown and buttons over the next couple days

**Comment by Kilvoctu** [comment]
You are awesome 👍
Take your time, I really am grateful for the help 👍👍

**Comment by sebaxakerhtc** [comment]
Dear @solareon 
I tried this PR, but it send just batch, not the images

**Comment by solareon** [comment]
@sebaxakerhtc thats correct. The individual images are still saved on the disk but I haven't had a chance to build the select for an individual image due to being busy with my day job. Hopefully this coming week I'll have more time to tinker with it.

**Comment by Kilvoctu** [comment]
Looks great @solareon! The UI/workflow is very nice, I like it a lot 👍👍

A few thoughts and things I'm noticing after doing a test run:

- I was going to use the 5th button slot on the row to extend the view for more commands, but since I've got no idea when I'll get around to doing that, putting ⬆️ there now is acceptable 👍

- I'm very particular on what slash commands are added and the order they're in 👀 

- The upscale is not working for me

**Comment by Kilvoctu** [comment]
> the views weren't playing nicely.

Also yeah, lol. Working with Discord Views is easily the most frustrating part of aiyabot development, for me.. 😅

**Comment by solareon** [comment]
Yep I'll tinker with that today and add it under the info stuff and the other documentation

**Comment by solareon** [comment]
@Kilvoctu alright I moved the batch stuff under the /info, added a context menu download to scoop all the images. Squashed a few more bugs with max grid sizes and removed the limit of only downloading 10 images at once from the drop down.

**Comment by Kilvoctu** [comment]
All right, I tried out the changes and everything looks good to me 👍 The ctx menu option is nice too.  
You are awesome @solareon. Not many people have contributed with a PR, and not only are you one of them, but you knocked out like the [biggest project](https://github.com/users/Kilvoctu/projects/18/views/1) on my list (and it's the first project I can close now). Thanks soooo much!

I'll get this merged and update wiki and such, then you can have a spot in the credits 💓💖

**Comment by solareon** [comment]
Glad I could help out. I like to try and contribute where I can to improve the stuff that I use. To be honest I didn't even know what the context menu options were until I was looking at the info documentation and was like "oh, that's where those are". Feel free to tag me on other issues/requests if I don't see them.

**Comment by sebaxakerhtc** [comment]
@solareon What the up-arrow button should do?
When i click it - it says use the drop-down menu.

@Kilvoctu Hey, try out my [upstream branch](https://github.com/sebaxakerhtc/myaiyabot/tree/upstream)
I used your batch-alt, then merged main (resolving conflicts) and after that added Live Previews and list of scripts in info.
Looks like working fine. If you like it i will try to make a PR.
Thank you!

**Comment by solareon** [comment]
@sebaxakerhtc the up arrow is used if you have a single image. Because we use decorators for the views you can't hide individual buttons so it stays there and just points you to use the drop down.

The live previews would be neat but should definitely be a configurable option so you don't burn up discord api hits

**Comment by Kilvoctu** [comment]
> Hey, try out my [upstream branch](https://github.com/sebaxakerhtc/myaiyabot/tree/upstream) I used your batch-alt, then merged main (resolving conflicts) and after that added Live Previews and list of scripts in info. Looks like working fine. If you like it i will try to make a PR. Thank you!

Heya, I took a look at it. The live previews seem to be using the code from phoenix-the-uncreative's fork. Personally, I don't like using people's code without permission, and on top of that their implementation isn't how I want to do it anyway lol.. 😅  
I was going to do my own version of progress update when I had time, as I prefer to edit the initial reply than creating a new message with progress update. And as solareon mentions, the concern of resources usage and API hits is something I think of, as well.

As for anything regarding scripts, I'm not too interested in that for this repo at this time (personally, I use a completely vanilla Web UI).

If it's good for you, that's great! That's what forks are for and it's the power of open-source 👍

**Pull request merged**
