### PR TITLE
feat: Implement compatibility with SD.Next

### PR DESCRIPTION
**Pull request by FoxxMD**
Originally based on https://github.com/hdtv35/aiyabot but with my own modifications so both backends can work

* Adds a `backend` global var and constants for setting the backend type
* backend is determined by endpoint GET at startup
* auth and model names are backend-dependent

~~This PR is **NOT** ready yet.~~ There are several SD.Next specific features in my own branch I want to pull in. But I wanted to get it out in the open in case anyone else using [SD.Next](https://github.com/vladmandic/automatic) wanted to give it a try and provide feedback.

### CODE REVIEW

**Comment by FoxxMD** [comment]
Everything is added:

* Full quality VAE draw option
* Gets loras from official endpoint (works for webui as well)

**Comment by Kilvoctu** [comment]
Looks like there are some conflicts. Could you resolve them, sorry it wouldn't have happened if I merged sooner 🙏

**Comment by FoxxMD** [comment]
Checking on an auth change...

**Comment by FoxxMD** [comment]
Ok, good to go.

**Pull request merged**
