### PR TITLE
Add sampler to auto-complete

### LINKED ISSUE #212: A1111 v1.6.0 - Samplers > 25
Hey,

I think it's legit to open an Issue for this, for an official and proper fix.

((: 

### Discussed in https://github.com/Kilvoctu/aiyabot/discussions/211

<div type='discussions-op-text'>

<sup>Originally posted by **wizz13150** September  4, 2023</sup>
Hey, 

there is too many Samplers in the last update.
Causing a 'choices >25' error at launch of the bot.

Not sure which samplers should be ignored, so i just added this in `settings.py` :

image

An existing bot will be 'fine', But this error also prevents the synchronization of commands, so it's **blocking** for fresh installations or modifications.
Annoying.
Maybe this should be in Issue 🤔

Cheers ! 🥂
</div>

### PR DESCRIPTION
**Pull request by solareon**
Fixes #212 and #216. Added sampler to autocomplete for settingscog and stablecog

### CODE REVIEW

**Comment by solareon** [comment]
The code was basically already there for all the others, just had to adapt for the samplers.

**Comment by chrismuzyn** [comment]
I've been cherry picking this commit for a while.  Can we get this merged?

**Comment by solareon** [comment]
I don't have write access on this repo so can't merge unfortunately =/

**Comment by Kilvoctu** [comment]
Sorry for the delay

**Pull request merged**
