### PR TITLE
added Url as option for initial image

### PR DESCRIPTION
**Pull request by Pyrotuna**
as requested from #19 
Note: Url **will** override init_image if both are present

### CODE REVIEW

**Comment by Kilvoctu** [comment]
Looks like it was a pretty simple thing 😄
So what I'm looking at is there's another option `url_image`, and if both `init_image` and `url_image` is set, then the latter takes priority. And there is some error handling for when no image is found in URL.

**Comment by Pyrotuna** [comment]
It was a really simple solution, just wanted to pr so issue #19 would get resolved, the remix part sounds way more complex and I'd need a lot more time to study the code and API

**Comment by Kilvoctu** [comment]
Yeah, the remixing, as I mentioned in that issue, is something I've been wanting too. I also feel like it'll take a good understanding of the code and API. It's also partly why I try to keep the code decently structured and commented, so a newbie like myself can understand easier.

Anyway, I tested the PR yesterday and it works great from what I recall. There were some minor cosmetic things, and I'll merge it after I remember what those are.
Again, thanks for all the help 👍👍

**Comment by Kilvoctu** [comment]
Hm I tried adding a commit, and github broke and lost my changes. I'll just merge first and update after, like last time 🤔

**Pull request merged**
