### PR TITLE
Generate fix + draw button + other model

### PR DESCRIPTION
**Pull request by wizz13150**
Hey,

hope you're fine !

I adjusted the Generate command this way :
- Edited core/setup_generate.py to download another model. It's just so much better ! (nothing implemented for existing folder)
- Adding 2 options : Number of prompts (1-5) and Max length (15-150 tokens).
- Adding a button for each generated prompt, to directly queue a Draw from it.

Seems robust to me. Had to adjust here and there.

Screenshots  : 

image
image
image

Cheers ! 🥂

### CODE REVIEW

**Comment by wizz13150** [comment]
huh, i should use git one day for my commits ...

**Comment by wizz13150** [comment]
Ah crap, the buttons break after a few minutes... huh

Don't know how to manage with this yet, even looking at the existing code, lol.

**Comment by solareon** [comment]
Welcome to the hell that is discord buttons and context menus lol. They break in all sorts or new and exciting ways when you least expect it.

**Comment by wizz13150** [comment]
ahahah !

Yeah, also noticed/realized the 4096 chars allowed for a discord message.
So it doesnt' fit my maximum allowed for /Generate when asking for 10 prompts of 250 tokens.

So i need to calculate the max amount generated and decrease the max prompt or length, or dynamically calculate this maybe.
Will see, not a blocking issue...

I'm less confident for the button, i don't want to complexify even more the code.
I don't close this PR yet, just as lab.

Cheers ! 🥂

**Comment by wizz13150** [comment]
Okay, let's start again from this and see.
A 'lil bit more homogeneous with the bot. Just a bit lol.

image


Result, For viewing pleasure :

image
image
image


Also, i think posting a single PR for both /generate and the progression message would be nice.
Had to add 2 more controls in it. 
Here is the actual visual :

image


Waiting to see if i can post a single PR or not.

**Comment by wizz13150** [comment]
Okay, this timeout arg was the trick.

Buttons still working after a while.

So, i'll wait and see what to edit to finalize this, would be cool to have a feedback about the logic/method, and then i'll post a single PR for both current ones.

Time to bed.

Cheers ! 🥂

**Comment by wizz13150** [comment]
hum, not bad, waiting to see if it's still working in an hour lol 😅

**Comment by wizz13150** [comment]
Found this, i'll dig.

https://github.com/Pycord-Development/pycord/blob/master/examples/views/persistent.py

**Comment by wizz13150** [comment]
I give up !

I think I'll dissect viewhandler.py and mimic what I see. 
Maybe I should use this file for my buttons, in fine.

**Comment by wizz13150** [comment]
So, i tried to implement my `generatecog.py` buttons-related code into viewhandler.py...
But it seems quite impossible for me to manage interactions properly...

Back to my initial approach, using only `generatecog.py`

Discord is a fucking joke !
Kind of pissed off atm, i literally got an headache from this.

**Pull request closed without merging**
