### PR TITLE
/Generate (prompt generator from short and simple text)

### PR DESCRIPTION
**Pull request by wizz13150**
Hey, 

Okay second try.. sorry for that.

What about a **/Generate** command, to generate a prompt from a simple text, using https://huggingface.co/Gustavosta/MagicPrompt-Stable-Diffusion
or else..

I'll leave this here.
Obviously not a python expert 😂, but the idea is here.
Add Torch and Transformers to requirements.txt, run a control for missing model files, and add the command to the bot.
Running on the CPU, so no conflict with image generation, also no need to be queued with in the same queue as images.

Feel free to delete if sounds dumb ((:
Ofc need to be improved, maybe using another queue.

Screen (of my sarcastic version of the bot) : 

image

### CODE REVIEW

**Comment by Kilvoctu** [comment]
Heya, code looks good and no additional steps for setup (aside from waiting for files to download). 👍  
Looks good to me, except can you not include that last commit? I like the messages.csv as they are right now. This is generally why people do PR's from a different branch aside from their main, lol.

**Comment by wizz13150** [comment]
ooops, my bad. I remove this rn !
Well, an error will pop if multiple request in a short time, a queue would be the best option, i think.

Here a screen :

image

Unfortunately, it's already late for me, heading for bed (:

**Comment by wizz13150** [comment]
one noob commit later..
The dedicated queue seems to work fine.

No need to mention other infos like the prompt, cause it's in the response. 
I think i'm not that bad here Sir !

Screen : 

image

**Comment by Kilvoctu** [comment]
Yeah, all looks good to me now. The queue logic is solid. Thanks so much for the PR!

**Pull request merged**
